gcode_interpreter:
  ros__parameters:
    # UR16e print-bed offsets in millimetres, relative to robot Base.
    origin_at_center: true
    x_offset: -778.0
    y_offset: -362.0
    z_offset: 196.42
    wrist_angle: 90.0

    # Speed and extrusion
    print_speed_multiplier: 1.0
    extrusion_scale_factor: 1.0
    first_layer_speed_factor: 1.0
    split_threshold: 45.0
